### ISSUE TITLE
How to change hair color?

### ISSUE THREAD

**Issue by codermckee** [MunchkinChen/FADING#3]
thanks for your amazing work.  I can change face feature of input image as the age increased, but the hair color changed little.

**Comment by gh-BumsooKim** [comment]
Hello, I'm generative AI researcher who have been researching in the field of Face Re-Aging. I am not the author of the FADING paper, but I would like to share some of the points mentioned above.

In the field of Face Re-Aging,
***hair style or color are generally not included in the target factors that researchers want to change.***

Many Face Re-Aging papers (LATS'20, HRFAE'20, RAGAN'21, SAM'22, AgeTransGAN'22, CUSP'22, FRAN'23, Video Face Re-Aging'23, PADA'23) also focused on generating/editing facial texture or modifying facial shape, not hair color.

So I don't think FADING can technically change hair color either. If you want, I would recommend using another different network or adding some components which can control the hair color into FADING network.

hope this helps,

**Comment by codermckee** [comment]
Thanks for your reply! Your answer has really resolved my confusions. 
Also, thank you for recommending the articles and other methods, these help a lot!

**Comment by codermckee** [comment]
@gh-BumsooKim Thanks for your reply! Your answer has really resolved my confusions.
Also, thank you for recommending the articles and other methods, these help a lot!

**Comment by gh-BumsooKim** [comment]
I'm glad it helped.

Additionally, I would like to share one thing related with hair color.

Basically, almost Face Re-Aging network used Age-Labeled dataset like FFHQ-Aging with unsupervised manner. Especially for StyleGAN-based approaches, those networks will inevitably face data bias or entanglement problems in the distribution of training datasets. Therefore, some networks (SAM, AgeTransGAN, and so on) based on GAN inversion and using the corresponding StyleGAN may generate hair color changes depending on the input target age like 85, whether the researcher intended it or not. This is because images of elderly people in training dataset may usually have white hair (this is assumption), so it can be considered as entanglement (for example, the model may generate an image of an elderly person's face with white hair. If I express it exaggeratedly, from the model's perspective, the image of an elderly person == white hair color). This entanglement problem is easily observed in StyleGAN-based approaches.

Hope this helps too, Have a good day!
